- name: Install packages
  become: true
  become_method: sudo
  apt: 
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - python3.6
    - git
    - python3-pip
    - python3-gunicorn
    - gunicorn

- name: Clone repository
  git: 
    repo: '{{ repository_url }}'
    dest: '{{ repository_path }}'
    force: yes

- name: Install requirements
  pip:
    requirements: '{{ repository_path }}/requirements.txt'

- name: Update db
  environment:
    FLASK_APP: app.py
    POSTGRESQL_URL: postgresql://{{ db_user }}:{{ db_password }}@localhost/{{ db_name }}
  shell: cd {{ repository_path }} && flask db upgrade

- name: Copy service config
  template:
    src: templates/gunicorn.service
    dest: /lib/systemd/system/gunicorn.service

- name: Register gunicorn service
  become: true
  become_user: root
  shell: systemctl enable gunicorn.service && service gunicorn start
